### ISSUE TITLE
Error: env GITHUB_TOKEN is not set

### ISSUE THREAD

**Issue by lacolaco** [k1LoW/gh-grep#21]
In my environment `gh grep` throws an error "Error: env GITHUB_TOKEN is not set". 
Other built-in commands from `gh` (like `gh repo`) work without any error. 

```
$ gh version
gh version 2.2.0 (2021-10-25)

$ gh auth status

github.com
  ✓ Logged in to github.com as lacolaco (***)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
```

I've just executed `gh extension` command for installation. Are there any additional steps?

**Comment by k1LoW** [comment]
Hi @lacolaco 

The gh extension is not able to take over the GitHub CLI settings.
In particular, gh-grep does more than the GitHub CLI has, so it can't even run the gh command internally.

Currently, you need to set environment variables for gh-grep.

**Comment by k1LoW** [comment]
> In particular, gh-grep does more than the GitHub CLI has, so it can't even run the gh command internally.

The above is slightly incorrect.
gh-grep is not using [`gh api`](https://cli.github.com/manual/gh_api) internally.

**Comment by lacolaco** [comment]
Thank you for answering. I see today I have to configure `GITHUB_TOKEN` in my environment.

**Comment by k1LoW** [comment]
Thank you!!

( If [config](https://github.com/cli/cli/tree/trunk/internal/config) goes out from `internal/` in [cli/cli](https://github.com/cli/cli), I'll deal with it! )

**Comment by gennaro-tedesco** [comment]
I came across the same, perhaps it is useful to specify it in the `README`? Moreover the `GITHUB_TOKEN` is generally created automatically by GitHub actions, so it may be unclear what secret exactly needs to be specified (for instance I did not understand correctly what to do myself).

**Comment by Baro1905** [comment]
https://github.com/k1LoW/gh-grep/issues/21#issuecomment-1028476263

**Comment by k1LoW** [comment]
> The gh extension is not able to take over the GitHub CLI settings.

Fixed!!!!
