### ISSUE TITLE
Error: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by suewonjp** [k1LoW/gh-grep#23]
Excellent tool! Thank you.

I've got `Error: bufio.Scanner: token too long` when searching a simple phrase for a very 1st hello world try.

I have no knowledge about go language, but it looks like people recommend `bufio.Reader.ReadLine` instead of `bufio.NewScanner`

https://stackoverflow.com/questions/21124327/how-to-read-a-text-file-line-by-line-in-go-when-some-lines-are-long-enough-to-ca

**Comment by k1LoW** [comment]
Thank you for your advice!
